# Generated by Django 3.0.6 on 2020-09-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta_destino', to='archivos.carpeta')),
            ],
        ),
    ]
