# Generated by Django 2.1.15 on 2020-11-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepto', to='prueba1.Departamento')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisiones',
            },
        ),
    ]
