# Generated by Django 3.0.7 on 2020-07-02 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 15, 34, 46, 352505, tzinfo=utc)),
        ),
    ]
