# Generated by Django 3.0.7 on 2020-07-02 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0002_auto_20200702_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 16, 44, 38, 74122, tzinfo=utc)),
        ),
    ]
