# Generated by Django 3.0.7 on 2020-07-21 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0003_auto_20200702_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 21, 46, 3, 772955, tzinfo=utc)),
        ),
    ]
