# Generated by Django 3.0.7 on 2020-07-21 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0005_auto_20200721_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 22, 1, 14, 344037, tzinfo=utc)),
        ),
    ]
