# Generated by Django 3.0.7 on 2020-07-22 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0019_auto_20200722_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 20, 4, 37, 412213, tzinfo=utc)),
        ),
    ]
