# Generated by Django 3.0.7 on 2020-07-22 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0020_auto_20200722_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 20, 5, 7, 635941, tzinfo=utc)),
        ),
    ]
