# Generated by Django 3.0.6 on 2020-09-12 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0022_auto_20200722_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2020, 9, 12, 22, 24, 1, 363584, tzinfo=utc)),
        ),
    ]
